name: IAC-main
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment?'
        default: 'DEVELOP'
        required: true
      resource_group:
        description: 'Target resource group?'
        default: 'GUITARS-DEVE-RG'
        required: true
jobs:
  iac:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "spinfo-guitars-kv"
        secrets: 'SA-ACCESS-KEY,SP-CLIENTID,SP-SUBSCRIPTIONID,SP-TENANTID,SP-PASSWORD'
      id: GetAccessInfo
    - uses: actions/checkout@v2
    - name: 'Terraform Build'
      run: |
        export ARM_CLIENT_ID="${{ steps.GetAccessInfo.outputs.SP-CLIENTID }}"
        export ARM_ACCESS_KEY="${{ steps.GetAccessInfo.outputs.SA-ACCESS-KEY }}"
        export ARM_SUBSCRIPTION_ID="${{ steps.GetAccessInfo.outputs.SP-SUBSCRIPTIONID }}"
        export ARM_TENANT_ID="${{ steps.GetAccessInfo.outputs.SP-TENANTID }}"
        export ARM_CLIENT_SECRET="${{ steps.GetAccessInfo.outputs.SP-PASSWORD }}" 
        terraform init
        terraform workspace select DEVE || terraform workspace new DEVE
        terraform plan -out=out.plan -var-file=terraform.tfvars -var="resource_group=${{ github.event.inputs.resource_group }}" -var="environment=${{ github.event.inputs.environment }}"
        terraform apply out.plan  
